var projetos = [
    {
        caminho: 'indice de referência',
        titulo: 'título indice 0',
        descricao: 'Descrição 0 Descrição de cada projeto ',
        qnteImgs: 0,
    },
    {
        caminho: 'alfabicho',
        titulo: 'Jogo TCC Alfabicho',
        descricao: 'Trabalho de Conclusão de curso (TCC) - Jogo educativo com temática de preservação ambiental.',
        qnteImgs: 16,
    },
    {
        caminho: 'ambar',
        titulo: 'Site Âmbar',
        descricao: 'Site desenvolvido para empresa de cenografia Âmbar.',
        qnteImgs: 5,
    },
    {
        caminho: 'assistente_virtual',
        titulo: 'Assistente Virtual',
        descricao: 'Assistente virtual criado para interatividade de cursos e-learning.',
        qnteImgs: 5,
    },
    {
        caminho: 'avarento',
        titulo: 'Site O Avarento',
        descricao: 'Site desenvolvido para a peça de teatro O Avarento.',
        qnteImgs: 5,
    },
    {
        caminho: 'cinco_e_videos',
        titulo: 'Edição de Vídeos',
        descricao: 'Edição e publicação em redes sociais de Videos para empresa 5º Elemento.',
        qnteImgs: 6,
    },
    {
        caminho: 'curso_cemig',
        titulo: 'Curso EAD CEMIG',
        descricao: 'Curso de EAD para empresa CEMIG.',
        qnteImgs: 4,
    },
    {
        caminho: 'curso_estrategia',
        titulo: 'Curso EAD Estratégia',
        descricao: 'Curso EAD Estratégia produzido para o Canal Minas Saúde da Fundação Renato Azeredo.',
        qnteImgs: 5,
    },
    {
        caminho: 'curso_hipertensao',
        titulo: 'Curso EAD Hipertensão',
        descricao: 'Curso EAD Hipertensão produzido para o Canal Minas Saúde da Fundação Renato Azeredo.',
        qnteImgs: 5,
    },
    {
        caminho: 'curso_sm',
        titulo: 'Curso EAD Saúde Mental',
        descricao: 'Curso EAD Saúde Mental produzido para o Canal Minas Saúde da Fundação Renato Azeredo.',
        qnteImgs: 5,
    },
    {
        caminho: 'cursos5e',
        titulo: 'Cursos EAD 5E',
        descricao: 'Diversos cursos EAD produzidos (ou editados) para empresa 5º Elemento - Design da Informação.',
        qnteImgs: 5,
    },
    {
        caminho: 'gtelecom',
        titulo: 'Site Gtetlecom',
        descricao: 'Site institucional para empresa Gtetlecom',
        qnteImgs: 5,
    },
    {
        caminho: 'jogo_dados',
        titulo: 'Jogo educativo temática dados',
        descricao: 'Jogo educativo temática dados para curso EAD do Canal Minas Saúde.',
        qnteImgs: 4,
    },
    {
        caminho: 'jogo_memoria',
        titulo: 'Jogo da Memória (Educativo)',
        descricao: 'Jogo da Memória (educativo) para o curso de Produção Multimídia',
        qnteImgs: 2,
    },
    {
        caminho: 'jogo_quebracabeca',
        titulo: 'Jogo Quebracabeça',
        descricao: 'Jogo quebracabeça (educativo) para o curso de Produção Multimídia',
        qnteImgs: 4,
    },
    {
        caminho: 'jogo_skate',
        titulo: 'Jogo Skate (Educativo)',
        descricao: 'Jogo educativo temática Skate para curso EAD do Canal Minas Saúde.',
        qnteImgs: 5,
    },
    {
        caminho: 'jogo_tiro',
        titulo: 'Jogo Tiro ao Alvo',
        descricao: 'Jogo Tiro ao Alvo (educativo) para o curso de Produção Multimídia.',
        qnteImgs: 3,
    },
    {
        caminho: 'mvvs',
        titulo: 'Site MVVS',
        descricao: 'Site institucional para empresa MVVS.',
        qnteImgs: 1,
    },
    {
        caminho: 'news',
        titulo: 'Newsletters',
        descricao: 'Newsletters para E-mail Marketing.',
        qnteImgs: 5,
    },
    {
        caminho: 'outros',
        titulo: 'Diversos',
        descricao: 'Serviços diversos prestados como criação de hotsites, consultorias, Artes para cases de DVD, sketch arquitetura, etc.',
        qnteImgs: 9,
    },
    {
        caminho: 'proposta_elearning',
        titulo: 'Proposta de Interface Visual',
        descricao: 'Proposta de Interface Visual (Projeto Gráfico de IDV) para Curso E-Learning.',
        qnteImgs: 4,
    },
    {
        caminho: 'rphoto',
        titulo: 'Hotsite RPhoto',
        descricao: 'Customização de Template para o Hotsite RPhoto.',
        qnteImgs: 3,
    },
    {
        caminho: 'site5e',
        titulo: 'Edição site 5E',
        descricao: 'Edição site da empresa 5º Elemento - Design da Informação.',
        qnteImgs: 1,
    },
    {
        caminho: 'proj_numar',
        titulo: 'Trabalho Voluntário Projeto NUMAR',
        descricao: 'Trabalho Voluntário de Criação de Manual Identidade Visual e peças gráficas para o Projeto Social NUMAR.',
        qnteImgs: 4,
    },
    {
        caminho: 'painel_fiemg',
        titulo: 'Painel FIEMG',
        descricao: 'Painel com cálculos ao longo do tempo afim de mensurar valores em uma apresentação para empresa FIEMG.',
        qnteImgs: 1,
    },
    {
        caminho: 'jogo_acampamento',
        titulo: 'Jogo educativo temática acampamento',
        descricao: 'Jogo educativo temática acampamento para curso EAD c.',
        qnteImgs: 5,
    },
    {
        caminho: 'mineiro_engenharia',
        titulo: 'Campanha Empresa Mmineiro Engenharia',
        descricao: 'Produção de Site, criação de novo logotipo, cartão de visitas e folder para empresa Mineiro Engenharia.',
        qnteImgs: 5,
    },
    {
        caminho: 'jogo_boliche',
        titulo: 'Jogo educativo temática boliche',
        descricao: 'Jogo educativo temática boliche para curso EAD do Canal Minas Saúde.',
        qnteImgs: 5,
    },
    {
        caminho: 'britos_engenharia',
        titulo: 'Campanha Completa Britos Engenharia',
        descricao: 'Campanha divulgação para empresa Britos Engenharia incluindo vídeo institucional, site, cartão de visita, páginas de redes sociais e Google analytics.',
        qnteImgs: 7,
    }
  ];